---
- hosts: web
  become: yes

  pre_tasks:
    - name: "Add repository for PHP 7.0."
      apt_repository: 
        repo="ppa:ondrej/php" 
        update_cache=yes

  roles:
    - role: geerlingguy.php
      php_version: "7.0"
      php_packages:
        - php7.0-common
        - php7.0-cli
        - php7.0-dev
        - php7.0-fpm
        - libpcre3-dev
        - php7.0-gd
        - php7.0-curl
        - php7.0-imap
        - php7.0-json
        - php7.0-opcache
        - php7.0-xml
        - php7.0-mbstring
      php_date_timezone: "Europe/London"
      php_mysql_package: php7.0-mysql
      php_fpm_daemon: php7.0-fpm
      php_webserver_daemon: nginx
      php_conf_paths:
        - /etc/php/7.0/fpm
        - /etc/php/7.0/apache2
        - /etc/php/7.0/cli
      php_extension_conf_paths:
        - /etc/php/7.0/fpm/conf.d
        - /etc/php/7.0/apache2/conf.d
        - /etc/php/7.0/cli/conf.d
      php_fpm_pool_conf_path: "/etc/php/7.0/fpm/pool.d/www.conf"
